export { default as authService } from './auth.service'
export { default as adminService } from './admin.service'
export { default as tokenService } from './token.service'
export { default as studentService } from './student.service'
export { default as fingerprintService } from './fingerprint.service'
