export { default as authValidation, type LoginSchema } from './auth.validation'
export { default as adminValidation } from './admin.validation'
export type * from './admin.validation'
export { default as studentValidation } from './student.validation'
export type * from './student.validation'
export { default as fingerprintValidation } from './fingerprint.validation'
export type * from './fingerprint.validation'
